###############################################################################
# Author: <Your Name>
# Name: TechNight-WebAPI-CICD (Workflow)
#
# Workflow used to package, deploy, and configure the TechNight-WebAPI
###############################################################################

name: TechNight-WebAPI-CICD

env:
  DOTNET_VERSION: '6.0'
  WEBAPP_BASE_PATH: 'My-WebAPI'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'My-WebAPI/**'
  # TODO: add pull request events to trigger the workflow
  pull_request:
    branches: [ "main" ]
    paths:
      - 'My-WebAPI/**'

  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual build from GitHub UI'

# Write permissions are the minimal required by the Publish Test Results action
# https://github.com/EnricoMi/publish-unit-test-result-action#permissions
permissions:
  checks: write
  pull-requests: write

jobs:

########################
# BUILD STAGE
########################
  build:
    runs-on: ubuntu-latest

    outputs:
      AZURE_WEBAPP_NAME: ${{ steps.setEnvVariables.outputs.AZURE_WEBAPP_NAME }}
      RESOURCE_GROUP: ${{ steps.setEnvVariables.outputs.RESOURCE_GROUP }} 

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # As of June 2023, GH offers no built-in way to pass environment variables to a
      # reusable workflow. This is a workaround as suggested in this thread: 
      # https://github.com/orgs/community/discussions/26671
      - name: Set variables to be passed to the reusable workflow
        id: setEnvVariables
        run: |
          echo "AZURE_WEBAPP_NAME=dryrun-webapp" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_GROUP=dryrun"        >> "$GITHUB_OUTPUT"

      # Add Action to Setup .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # TODO: Add Action to Build Web App
      - name: Build Web App
        run: dotnet build ${{ env.WEBAPP_BASE_PATH }}/WebAPI -c Release

      # TODO: Add Action to Run Unit Tests
      - name: Run Unit Tests
        run: dotnet test ${{ env.WEBAPP_BASE_PATH }}/WebAPI -c Release --logger "trx;LogFileName=testresults.trx"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ env.WEBAPP_BASE_PATH }}/**/*.trx

      # TODO: Add Action to Publish Web App 
      - name: Publish Web App
        run: dotnet publish ${{ env.WEBAPP_BASE_PATH }}/WebAPI -c Release -o ${{ env.DOTNET_ROOT }}/technight-webapi

      # TODO: Add Action to Upload Web App Artifacts for Deployment
      - name: Upload Web App Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ${{ env.DOTNET_ROOT }}/technight-webapi

      # TODO: Add Action to Upload Bicep Template for Deployment
      - name: Upload Bicep Template
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: arm-templates/webapp/azuredeploy.bicep
          if-no-files-found: error

########################
# DEVELOPMENT STAGE 
########################
  dev:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment: Dev

    # TODO: declare environment variables for the dev environment prefix
    env:
      ENVIRONMENT_PREFIX: DEV
      #ENVIRONMENT: DEVELOPMENT
      #AZURE_WEBAPP_NAME: ${{ needs.build.outputs.AZURE_WEBAPP_NAME }}
      #RESOURCE_GROUP: ${{ needs.build.outputs.RESOURCE_GROUP }}
      #STARTUP_COMMAND: "dotnet WebAPI.dll"
      #AZURE_WEBAPP_SKU: B1
    steps:

      # Download the artifacts from the build job (actions/download-artifact@v3)
      - name: download-artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      #TODO: Add action to login to Azure (azure/login@v1)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      #TODO: Add action to deploy the Web App Bicep Template (azure/arm-deploy@v1)
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.ENVIRONMENT_PREFIX }}-${{ needs.build.outputs.RESOURCE_GROUP }}
          template: 'azuredeploy.bicep'
          parameters: >
            envPrefix=${{ env.ENVIRONMENT_PREFIX }}
            webAppName=${{ needs.build.outputs.AZURE_WEBAPP_NAME }}
            sku="B1"
          failOnStdErr: false
      #TODO: Add action to deploy the Web App Artifacts (azure/webapps-deploy@v2)
      - name: Deploy Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.ENVIRONMENT_PREFIX }}-${{ needs.build.outputs.AZURE_WEBAPP_NAME }}
          package: ${{steps.download.outputs.download-path}}
          startup-command: 'dotnet WebAPI.dll'
      #TODO: Add action to configure the Web App Settings (azure/appservice-settings@v1)
      - name: Configure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.ENVIRONMENT_PREFIX }}-${{ needs.build.outputs.AZURE_WEBAPP_NAME }}
          app-settings-json: ${{ secrets.APP_SETTINGS }}
          connection-strings-json: ${{ secrets.CONNECTION_STRINGS }}
      #TODO: Add action to log out of Azure 
      - name: Azure Logout
        uses: azure/logout@v1

##############################
# PRODUCTION STAGE (FOR LATER)
##############################
#  prd:
      # without the below if statement the job will be displayed as "failed" if a change 
      # isn't coming from the develop or main branch
#      if: github.ref == 'refs/heads/main' 
#      needs: [build, dev]
#      uses: ./.github/workflows/webapp-deploy-template.yml
#      permissions:
#          contents: none
#      with:
#        ENVIRONMENT_PREFIX: PROD
#        ENVIRONMENT: PRODUCTION
#        AZURE_WEBAPP_NAME: ${{ needs.build.outputs.AZURE_WEBAPP_NAME }}
#        RESOURCE_GROUP: ${{ needs.build.outputs.RESOURCE_GROUP }}
#        STARTUP_COMMAND: "dotnet WebAPI.dll"
#        AZURE_WEBAPP_SKU: B1
#      secrets: inherit
